export const invoices = [
  {
    name: "Classical Guitar",
    desc: "Guitar classes ",
    instructor: "Ms. Jane Doe",
    instrument: "Guitar",
    day: "Wednesday",
    student: "26",
    price: "$60",
    status: "Active",
  },
  {
    name: "Electric Guitar Masterclass",
    desc: "Advanced lessons in playing the electric guitar.",
    instructor: "Dr. Sarah Johnson",
    instrument: "Electric Guitar",
    day: "Thursday",
    student: "15",
    price: "$75",
    status: "Active",
  },
  {
    name: "Piano",
    desc: "Get started with playing the piano.",
    instructor: "Ms. Emily Turner",
    instrument: "Piano",
    day: "Tuesday",
    student: "30",
    price: "$55",
    status: "Active",
  },
  {
    name: "Drumming Essentials",
    desc: "Learn the basics of drumming techniques.",
    instructor: "Mr. Mark Anderson",
    instrument: "Drums",
    day: "Thursday",
    student: "15",
    price: "$70",
    status: "Closed",
  },
  {
    name: "Violin Mastery",
    desc: "Advanced violin techniques for experienced players.",
    instructor: "Dr. Jessica Lee",
    instrument: "Violin",
    day: "Wednesday",
    student: "12",
    price: "$80",
    status: "Closed",
  },
  {
    name: "Saxophone Jazz Ensemble",
    desc: "Join a jazz ensemble and play the saxophone.",
    instructor: "Mr. Charles Parker",
    instrument: "Saxophone",
    day: "Monday",
    student: "20",
    price: "$65",
    status: "Closed",
  },
  {
    name: "Flute for All Ages",
    desc: "Learn to play the flute, suitable for all ages.",
    instructor: "Ms. Sarah Miller",
    instrument: "Flute",
    day: "Friday",
    student: "25",
    price: "$60",
    status: "Closed",
  },

  {
    name: "Bass Guitar Fundamentals",
    desc: "Learn the basics of playing the bass guitar.",
    instructor: "Mr. David Bassman",
    instrument: "Bass Guitar",
    day: "Tuesday",
    student: "18",
    price: "$70",
    status: "Closed",
  },
  {
    name: "Trumpet for Beginners",
    desc: "Get started with playing the trumpet.",
    instructor: "Ms. Laura Trumpet",
    instrument: "Trumpet",
    day: "Thursday",
    student: "10",
    price: "$65",
    status: "Archived",
  },
  {
    name: "Harmonica Jam Sessions",
    desc: "Join harmonica jam sessions with fellow enthusiasts.",
    instructor: "Mr. Harmonica Harry",
    instrument: "Harmonica",
    day: "Wednesday",
    student: "14",
    price: "$55",
    status: "Archived",
  },
  {
    name: "Cello Masterclass",
    desc: "Advanced cello techniques for experienced players.",
    instructor: "Dr. John Cellist",
    instrument: "Cello",
    day: "Monday",
    student: "8",
    price: "$90",
    status: "Archived",
  },
  {
    name: "Keyboard for Kids",
    desc: "Introductory keyboard lessons for children.",
    instructor: "Ms. Emily Keys",
    instrument: "Keyboard",
    day: "Friday",
    student: "22",
    price: "$45",
    status: "Active",
  },
];

export const studentData = [
  {
    RegNo: "43422",
    EnrNo: "1563124",
    Fname: "John",
    Lname: "Doe",
    Cname: "Percussion",
    Course: "3",
    Fees: "$300",
    RegDate: "01-06-2023",
    EnrDate: "12-08-223",
  },

  {
    RegNo: "43423",
    EnrNo: "1563125",
    Fname: "Jane",
    Lname: "Smith",
    Cname: "Guitar",
    Course: "2",
    Fees: "$250",
    RegDate: "02-06-2023",
    EnrDate: "13-08-2023",
  },
  {
    RegNo: "43424",
    EnrNo: "1563126",
    Fname: "Michael",
    Lname: "Johnson",
    Cname: "Violin",
    Course: "4",
    Fees: "$400",
    RegDate: "03-06-2023",
    EnrDate: "14-08-2023",
  },
  {
    RegNo: "43425",
    EnrNo: "1563127",
    Fname: "Sarah",
    Lname: "Williams",
    Cname: "Flute",
    Course: "1",
    Fees: "$150",
    RegDate: "04-06-2023",
    EnrDate: "15-08-2023",
  },
  {
    RegNo: "43426",
    EnrNo: "1563128",
    Fname: "David",
    Lname: "Brown",
    Cname: "Piano",
    Course: "3",
    Fees: "$300",
    RegDate: "05-06-2023",
    EnrDate: "16-08-2023",
  },
  {
    RegNo: "43427",
    EnrNo: "1563129",
    Fname: "Emily",
    Lname: "Davis",
    Cname: "Saxophone",
    Course: "2",
    Fees: "$250",
    RegDate: "06-06-2023",
    EnrDate: "17-08-2023",
  },
];
